#!/bin/bash 
#!/bin/ba School is so cool!" 
#!/bin/bash 

echo "ALX"

echo "ALX"

echo "ALX School"
echo "ALX School"
#!/bin/bash 
#!/bin/ba School is so cool!" 
#!/bin/bash 

echo "ALX"

echo "ALX"

echo "ALX School"
#!/bin/bash 

echo "ALX"
#!/bin/bash 

echo "ALX"
